'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.42000
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

<Assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("textfile1.txt"),  _
 Assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("%d0%91%d0%b5%d0%b7%d1%8b%d0%bc%d1%8f%d0%bd%d0%bd%d1%8b%d0%b910.exe"),  _
 Assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("%d0%91%d0%b5%d0%b7%d1%8b%d0%bc%d1%8f%d0%bd%d0%bd%d1%8b%d0%b912.exe"),  _
 Assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("%d0%91%d0%b5%d0%b7%d1%8b%d0%bc%d1%8f%d0%bd%d0%bd%d1%8b%d0%b913.exe"),  _
 Assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("%d0%91%d0%b5%d0%b7%d1%8b%d0%bc%d1%8f%d0%bd%d0%bd%d1%8b%d0%b914.exe"),  _
 Assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("%d0%91%d0%b5%d0%b7%d1%8b%d0%bc%d1%8f%d0%bd%d0%bd%d1%8b%d0%b915.exe"),  _
 Assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("%d0%91%d0%b5%d0%b7%d1%8b%d0%bc%d1%8f%d0%bd%d0%bd%d1%8b%d0%b916.exe"),  _
 Assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("%d0%91%d0%b5%d0%b7%d1%8b%d0%bc%d1%8f%d0%bd%d0%bd%d1%8b%d0%b93.exe"),  _
 Assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("%d0%91%d0%b5%d0%b7%d1%8b%d0%bc%d1%8f%d0%bd%d0%bd%d1%8b%d0%b98.exe"),  _
 Assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("%d0%91%d0%b5%d0%b7%d1%8b%d0%bc%d1%8f%d0%bd%d0%bd%d1%8b%d0%b99.exe")> 

